name: Continuous Integration

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: |
          cargo fmt --check
          if [ $? -ne 0 ]; then
            echo "::error::Code formatting check failed"
            exit 1
          fi

      - name: Run clippy
        run: |
          cargo clippy -- -D warnings
          if [ $? -ne 0 ]; then
            echo "::error::Clippy check failed"
            exit 1
          fi

      - name: Run tests
        run: |
          cargo test --release
          if [ $? -ne 0 ]; then
            echo "::error::Tests failed"
            exit 1
          fi
